### ISSUE TITLE
How to deal with custom events that have periods in their name

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/language-tools#1563]
### Describe the bug

Using Svelte 3.49, TypeScript, and Bootstrap 5.2, I setup an event handler for a Bootstrap Modal dialog (that works fine):
```html
<div on:shown.bs.modal={() => focusField.focus()} class="modal fade" id="announcementModal" aria-labelledby="announcementModalTitle">
```
...but I get a TypeScript warning for "on" in the above code...
```
(property) onshown: true
Type '{ onshown: true; }' is not assignable to type 'HTMLProps<HTMLDivElement>'.
  Property 'onshown' does not exist on type 'HTMLProps<HTMLDivElement>'.ts(2322)
Identifier expected.ts(1003)
```

Tried adding this to my global.d.ts:
```
declare namespace svelte.JSX {
  interface HTMLProps<HTMLDivElement> {
    'shown.bs.modal': (e: CustomEvent) => void
  }
}
```
...but it doesn't help. TypeScript seems to think the declaration should be `onshown: boolean` but that's only part of the Bootstrap Modal event name. I guess it stops at the first period. Vue.js supports quoted event names like `v-on="{ 'hide.bs.modal': handleModalClose }"`. Could not find the same for Svelte but again, the event handler works fine - only the typing is an issue.

Any thoughts on how to properly type this? 

### Reproduction

See above.

### Expected behaviour

Ability to properly type event handlers related to Bootstrap from Svelte.

### System Info

- OS: macOS 12.4
- IDE: VS Code 1.69.2
- Svelte: 3.49
- Bootstrap: 5.2.0

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="999" alt="image" src="https://user-images.githubusercontent.com/5770938/179992961-da65b210-b000-49f2-8f00-06b15ca3354d.png">

**Comment by nstuyvesant** [comment]
Seems like the detection of the event name show go from "on:" until the "=".

**Comment by dummdidumm** [comment]
This works only in the new transformation because of the dot in the event name. See [this issue]() for info on how to turn it on. Typing the additional event is achieved by adding this to your .d.ts file:
```ts
declare namespace svelte.JSX {
	interface HTMLAttributes<T> {
		'onshown.btn': (e: CustomEvent) => void;
	}
}
```

Note that both the namespace and way how to type the event will change with the new transformation soon (but you can continue to type it like shown here and it will get picked up).

**Comment by nstuyvesant** [comment]
OK - what you wrote is close to what I had...
```typescript
declare namespace svelte.JSX {
  interface HTMLProps<HTMLDivElement> {
    'shown.bs.modal': (e: CustomEvent) => void
  }
}
```

So I have to change `HTMLProps<HTMLDivElement>` to `HTMLAttributes<T>`?

**Comment by nstuyvesant** [comment]
One thing I should mention for other people's benefit... even though the TypeScript issue was resolved with the addition to global.d.ts and turning on the VS Code Svelte Setting "Use new transformation", svelte-check will still report these as issues unless `--use-new-transformation` is added to the command line (or npm script for check and check:watch).

**Comment by dummdidumm** [comment]
Closing because the new transformation is now enabled by default.

**Comment by theodorejb** [comment]
I'm still getting errors from `svelte-check` when I try to handle custom events with a period in their name.

I added the following to my `app.d.ts` file per the above comments:

```typescript
declare namespace svelte.JSX {
    interface HTMLAttributes<T> {
        "onhidden.bs.modal"?: (e: CustomEvent) => void;
    }
}
```

In my component I have this Bootstrap modal element:

```html
<div on:hidden.bs.modal={handleHide} class="modal" id="videoModal" aria-hidden="true"></div>
```

When I run `svelte-check`, it produces 4 errors from the above line in my component:

```
c:\code\main\src\routes\home\+page.svelte:189:8
Error: Identifier expected. (ts)

c:\code\main\src\routes\home\+page.svelte:189:86
Error: Unexpected token. Did you mean `{'>'}` or `&gt;`? (ts)

c:\code\main\src\routes\home\+page.svelte:189:89
Error: Expected corresponding closing tag for JSX fragment. (ts)

c:\code\main\src\routes\home\+page.svelte:189:6
Error: Type '{ onhidden: true; }' is not assignable to type 'HTMLProps<HTMLDivElement>'.
  Property 'onhidden' does not exist on type 'HTMLProps<HTMLDivElement>'. Did you mean 'hidden'? (ts)
```

Is this a bug in svelte-check, or is there something I'm missing with how to use custom elements with a period in their name?

It seems like it is failing to correctly parse the event name.
