### ISSUE TITLE
Property with an initial default value can get a undefined excluding TypeScript type while still becoming undefined during runtime

### ISSUE THREAD

**Issue by janvogt** [sveltejs/language-tools#2236]
### Describe the bug

According to https://github.com/sveltejs/svelte/issues/4442 props' default values are really *initial* values as they are only used when a component is first created. While I consider this, [as](https://github.com/sveltejs/svelte/issues/1467) [well](https://github.com/sveltejs/svelte/issues/3251) [as](https://github.com/sveltejs/svelte/issues/3063) [others](https://github.com/sveltejs/svelte/issues/4442) [who've](
https://github.com/sveltejs/svelte/issues/5673) [created](https://github.com/sveltejs/kit/issues/7178) [issues](https://github.com/sveltejs/svelte/issues/8020) [bevore](https://github.com/sveltejs/svelte/issues/9078) me, to be a rather unintuitive design decision, I assume there to be good reasons for it.

However, after spending over half a day tracking down this issue from an obscure exception thrown in a production app, I think it remains at least a bug in Svelte's TypeScript implementation. We were able to type an optional property that had an initial value with a type that excludes `undefined`. However, the value of that property may very much become `undefined` during runtime.

To be specific, I belive I should not be able do this: 

```svelte
<script lang="ts">
  export let optional: string = "this may be undefined, since this is 'only' an inital value!"
</script>
```

This is essentially a loaded footgun.

While I rate this as an annoyance, I cannot stress enough how much this defeats the core reason we use TypeScript in the first place.

If this will not be fixed, are there some ways to automatically prevent such flawed uses, i.e. intital values when they really should be a default?

This exact problem has been [described in a comment](https://github.com/sveltejs/svelte/issues/5673#issuecomment-901005959) before, as well in [this issue in sveltejs language-tools]( https://github.com/sveltejs/language-tools/issues/1167). The reason to close the latter, is pretty murky to me.

### Reproduction

This is a short repro simplified from our use case, unfortunately the repl does not support TypeScript. https://svelte.dev/repl/1448697c1adc4f31b658f5207747dece?version=3.29.4

### System Info

```shell
System:
    OS: Linux 6.1 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (4) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 10.71 GB / 15.26 GB
    Container: Yes
    Shell: 3.6.4 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 20.9.0 - /nix/store/a1hckfqzyys4rfgbdy5kmb5w0zdr55i5-nodejs-20.9.0/bin/node
    npm: 10.1.0 - /nix/store/a1hckfqzyys4rfgbdy5kmb5w0zdr55i5-nodejs-20.9.0/bin/npm
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Let's wait with proceeding this until we have decided if we want to switch the default behavior in Svelte 5.

**Comment by PascalHonegger** [comment]
> Let's wait with proceeding this until we have decided if we want to switch the default behavior in Svelte 5.


Is there an update on this issue now that Svelte 5 is further along in it's implementation?

**Comment by alshain** [comment]
Honestly, I would say this is more than just an annoyance. When you're just working on your own code, it's an annoyance. When you're working with libraries that aren't aware of this issue, it's a proper minefield. Could I go in and submit a PR for everything I come across? Sure. But I'm sure that 99% of the issues are because Svelte made a choice that is unwise in retrospect.

https://svelte.dev/repl/b71c5df8c24c4221a1c8b13184455375?version=3.46.6

**Comment by dm-de** [comment]
My "solution" today is:
1) I use default definitions where possible
2) If I pass a variable to prop, and if this variable can be undefined, I add same default (double code!) on top of that:
<Child value={myvalue || 'default'} />

**Comment by janvogt** [comment]
This issue was explicitly not about Svelte 4's default behaviour but about the language-tools wrong TypeScript type within a component. I don't get what this - certainly laudable - change in Svelte 5 fixes about this issue?

**Comment by dummdidumm** [comment]
Because the runtime behavior now matches the TS type definition

**Comment by janvogt** [comment]
I got this. However: Svelte 5 is not released. Svelte 4 or even 3 codebases are pretty much a thing, and IMHO will be for quite a while. Nothing has changed for them regarding this issue.

If the reason for closing is that language-tools wont support anything less than svelte 5 anymore, this should be at least closed as *wontfix* instead of *completed.* Otherwise it's very misleading.

**Comment by dummdidumm** [comment]
It's closed as in fixed in Svelte 5. We won't/can't backport this as changing this would be a breaking change

**Comment by janvogt** [comment]
I feel, as the OP of this issue, it should have some weight, when I say, that this is not resolved. Of course, it's your project and you are free to close any issue you want even without actually adressing them.

With Svelte 5 this issue might not exist anymore, but it's certainly not fixed.

Tbc: As [explicitely stated earlier](https://github.com/sveltejs/language-tools/issues/2236#issuecomment-1865326626) this issue is **not** with the weird behaviour around default values that Svelte <5 exhibits, but about the language tools using wrong types in many svelte projects. Having the right types in Svelte 5 projects is cool, but not a fix. 

But yaeh, I will not continue to argue any further. It is what it is.

**Comment by dummdidumm** [comment]
As stated earlier, this would be a huge breaking change (many people's projects would be littered with type errors), which is why we're not fixing this for Svelte 4.
